# Port
server.port=8081

# Limite taille requête pour images base64
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-form-post-size=10MB
server.tomcat.max-swallow-size=10MB

# H2 - Base de données (fichier persistant)
spring.datasource.url=jdbc:h2:file:./data/shopflowdb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
jwt.secret=shopflow_super_secret_key_2024_very_long_string_minimum_512_bits_abcdefghijklmnop
jwt.expiration=86400000
jwt.refresh-expiration=604800000